using CRISP.Adr;
using Microsoft.Extensions.Logging;

namespace CRISP.Enterprise.Ownership;

/// <summary>
/// Establishes clear code ownership from day one via CODEOWNERS file (GitHub)
/// or ownership documentation and branch policies (Azure DevOps).
/// </summary>
public sealed class OwnershipModule : IEnterpriseModule
{
    private readonly ILogger<OwnershipModule> _logger;

    public OwnershipModule(ILogger<OwnershipModule> logger)
    {
        _logger = logger;
    }

    public string Id => "ownership";
    public string DisplayName => "Code Ownership";
    public int Order => 400;

    public bool ShouldRun(ProjectContext context) => true;

    public async Task<ModuleResult> ExecuteAsync(ProjectContext context, CancellationToken cancellationToken = default)
    {
        var filesCreated = new List<string>();
        var scmConfigActions = new List<string>();

        try
        {
            if (context.ScmPlatform.Equals("github", StringComparison.OrdinalIgnoreCase))
            {
                // Generate CODEOWNERS file
                var codeownersDir = Path.Combine(context.WorkspacePath, ".github");
                Directory.CreateDirectory(codeownersDir);

                var codeownersPath = Path.Combine(codeownersDir, "CODEOWNERS");
                var codeownersContent = GenerateCodeowners(context);
                await File.WriteAllTextAsync(codeownersPath, codeownersContent, cancellationToken);
                filesCreated.Add(".github/CODEOWNERS");
                scmConfigActions.Add("codeowners:created");
            }
            else
            {
                // Generate ownership documentation for Azure DevOps
                var docsDir = Path.Combine(context.WorkspacePath, "docs");
                Directory.CreateDirectory(docsDir);

                var ownershipPath = Path.Combine(docsDir, "ownership.md");
                var ownershipContent = GenerateOwnershipMd(context);
                await File.WriteAllTextAsync(ownershipPath, ownershipContent, cancellationToken);
                filesCreated.Add("docs/ownership.md");
                scmConfigActions.Add("ownership:documented");
            }

            // Record ADR
            var mechanism = context.ScmPlatform.Equals("github", StringComparison.OrdinalIgnoreCase)
                ? "CODEOWNERS file"
                : "Azure DevOps reviewer policies";

            var owners = context.Owners.Count > 0
                ? string.Join(", ", context.Owners)
                : context.TeamName ?? "team (to be configured)";

            context.DecisionCollector.Record(
                title: $"Establish code ownership via {mechanism}",
                context: "Clear code ownership ensures that the right people review changes and are notified of issues.",
                decision: $"Configure {mechanism} with {owners} as default owners.",
                rationale: "Explicit ownership reduces review bottlenecks and ensures domain experts review relevant changes.",
                category: AdrCategory.CodeOwnership,
                consequences: [
                    "Pull requests automatically request reviews from code owners",
                    "Ownership is visible and documented",
                    "New team members can identify domain experts"
                ],
                relatedFiles: filesCreated
            );

            return new ModuleResult
            {
                ModuleId = Id,
                Success = true,
                FilesCreated = filesCreated,
                ScmConfigActions = scmConfigActions
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Ownership module failed");
            return ModuleResult.Failed(Id, ex.Message);
        }
    }

    private static string GenerateCodeowners(ProjectContext context)
    {
        var owners = GetOwnersString(context);

        return $"""
            # Code Owners — auto-generated by CRISP
            # See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

            # Default owners for everything
            * {owners}

            # CI/CD pipeline changes require team review
            .github/ {owners}

            # Documentation
            docs/ {owners}

            # Infrastructure
            Dockerfile {owners}
            docker-compose*.yml {owners}

            # Security-sensitive files
            SECURITY.md {owners}
            .env.example {owners}
            """;
    }

    private static string GenerateOwnershipMd(ProjectContext context)
    {
        var teamName = context.TeamName ?? "Platform Team";
        var teamEmail = context.TeamEmail ?? "team@example.com";
        var owners = context.Owners.Count > 0
            ? string.Join(", ", context.Owners)
            : "TBD";

        return $"""
            # Code Ownership

            This document defines ownership and review responsibilities for this project.

            ## Team Ownership

            | Area | Owner(s) | Contact |
            |------|----------|---------|
            | Overall | {teamName} | {teamEmail} |
            | CI/CD Pipelines | {teamName} | {teamEmail} |
            | Infrastructure | {teamName} | {teamEmail} |
            | Security | {teamName} | {teamEmail} |

            ## Individual Owners

            {(context.Owners.Count > 0 ? string.Join("\n", context.Owners.Select(o => $"- {o}")) : "- TBD: Add individual code owners")}

            ## Review Policy

            All pull requests to `{context.DefaultBranch}` require approval from at least one code owner.

            ### Required Approvals

            - **Default branch (`{context.DefaultBranch}`)**: 1 approval minimum
            - **Release branches**: 2 approvals recommended
            - **Hotfix branches**: 1 approval with expedited review

            ### Review Guidelines

            1. Review code for correctness, security, and maintainability
            2. Provide constructive feedback
            3. Approve only when confident in the changes
            4. Request changes if issues are found

            ## Escalation

            For urgent issues or when code owners are unavailable:

            1. Contact {teamEmail}
            2. Escalate to team lead
            3. Document exceptions in PR comments

            ---

            *This ownership document was generated by [CRISP](https://github.com/strali/crisp).*
            """;
    }

    private static string GetOwnersString(ProjectContext context)
    {
        if (context.Owners.Count > 0)
        {
            // Ensure GitHub usernames have @ prefix
            var owners = context.Owners.Select(o => o.StartsWith('@') ? o : $"@{o}");
            return string.Join(" ", owners);
        }

        if (!string.IsNullOrEmpty(context.TeamName))
        {
            var teamSlug = context.TeamName.ToLowerInvariant().Replace(" ", "-");
            return $"@{context.GitHubOwner}/{teamSlug}";
        }

        // Placeholder for unconfigured ownership
        return "# TODO: Add code owners (e.g., @your-team)";
    }
}
