using System.Text;

namespace CRISP.Adr;

/// <summary>
/// Generates the ADR index/README file.
/// </summary>
public sealed class AdrIndexGenerator
{
    /// <summary>
    /// Generates the index README.md content for the ADR directory.
    /// </summary>
    /// <param name="decisions">All ADR decisions to include in the index.</param>
    /// <param name="includeMetaAdr">Whether to include the meta-ADR (0000) in the index.</param>
    /// <param name="metaAdrDate">Date for the meta-ADR if included.</param>
    /// <returns>Markdown content for the index file.</returns>
    public string Generate(
        IReadOnlyList<AdrDecision> decisions,
        bool includeMetaAdr = true,
        DateOnly? metaAdrDate = null)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Architecture Decision Records");
        sb.AppendLine();
        sb.AppendLine("This directory contains Architecture Decision Records (ADRs) for this project.");
        sb.AppendLine("ADRs document significant architectural decisions made during project setup and development.");
        sb.AppendLine();
        sb.AppendLine("> These initial ADRs were generated by [CRISP](https://github.com/strali/crisp) during project scaffolding.");
        sb.AppendLine("> New decisions should be added following the [template](template.md).");
        sb.AppendLine();
        sb.AppendLine("## Decisions");
        sb.AppendLine();
        sb.AppendLine("| # | Title | Status | Date | Category |");
        sb.AppendLine("|---|---|---|---|---|");

        // Add meta-ADR row if included
        if (includeMetaAdr)
        {
            var date = metaAdrDate ?? DateOnly.FromDateTime(DateTime.UtcNow);
            sb.AppendLine($"| [0000](0000-record-architecture-decisions.md) | Record architecture decisions | Accepted | {date:yyyy-MM-dd} | process |");
        }

        // Sort decisions by number and add rows
        var sortedDecisions = decisions.OrderBy(d => d.Number).ToList();

        foreach (var decision in sortedDecisions)
        {
            var fileName = decision.GetFileName();
            var status = decision.Status.ToString();
            sb.AppendLine($"| [{decision.Number:D4}]({fileName}) | {decision.Title} | {status} | {decision.Date:yyyy-MM-dd} | {decision.Category} |");
        }

        sb.AppendLine();

        return sb.ToString();
    }
}
